### ISSUE TITLE
запахло сочным bytestream от crazorniki

### ISSUE THREAD

**Issue by moonbrawl** [CrazorTheCat/BSDS-V42#1]
Русский военный корабль, иди на CPPDefs.py
Когда битстрим и онлайн бои на srythonnn?
Когда нормальный качественный код?
Когда закончится война на Украине?

Ну что это блять, куча отборного дерьма от самого кразорчика, свежайшее.

**Comment by TheAcelot** [comment]
bsds v49 when??? Че за кринжовый байтсрим а??? или у сразоров мозг = 0??

**Comment by shark01d** [comment]
@TheAcelot лох, я уже делаю зимбабве бравл в49, пока прожекст срдсдср только на 42 🥰🥰🥰 один байстримтст зимбабаве ?равл в49 лутше всево бсдсд

**Comment by moonbrawl** [comment]
> @TheAcelot лох, я уже делаю зимбабве бравл в49, пока прожекст срдсдср только на 42 🥰🥰🥰 один байстримтст зимбабаве ?равл в49 лутше всево бсдсд

шраак, легенда ураааа, привет!!!!1

**Comment by TheAcelot** [comment]
> @TheAcelot лох, я уже делаю зимбабве бравл в49, пока прожекст срдсдср только на 42 🥰🥰🥰 один байстримтст зимбабаве ?равл в49 лутше всево бсдсд

ем я твой рот ебал крч

**Comment by moonbrawl** [comment]
> > @TheAcelot лох, я уже делаю зимбабве бравл в49, пока прожекст срдсдср только на 42 🥰🥰🥰 один байстримтст зимбабаве ?равл в49 лутше всево бсдсд
> 
> ем я твой рот ебал крч

![IMG_20220302_212704_471.jpg](https://user-images.githubusercontent.com/100240269/156644655-49d34c1f-c8e2-4229-b903-573c33da492e.jpg)
